apiVersion: apps/v1
kind: Deployment
metadata:
  name: tracing-node
  labels:
    app: tracing-node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tracing-node
  template:
    metadata:
      labels:
        app: tracing-node
    spec:
      containers:
      - name: tracing-node
        image: lab/tracing-node:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8081
        - containerPort: 50051
        env:
        - name: OTEL_SERVICE_NAME
          value: "tracing-node-service"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://otel-collector:4318"
        - name: OTEL_TRACES_EXPORTER
          value: "otlp"
        - name: GRPC_PORT
          value: "50051"
---
apiVersion: v1
kind: Service
metadata:
  name: tracing-node
spec:
  selector:
    app: tracing-node
  ports:
    - name: http
      protocol: TCP
      port: 8081
      targetPort: 8081
    - name: grpc
      protocol: TCP
      port: 50051
      targetPort: 50051
  type: ClusterIP
